spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/mooc_manager?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456

mybatis:
  mapper-locations: classpath:/mapper/*
  configuration:
    mapUnderscoreToCamelCase: true

#baseInfo
api-url: /api

server:
  port: 8080