ALIYUNCALLBACKHOST: 阿里的回调服务器地址
myconfig.aliyun:
  accessId: ''
  accessKey: ''
  endpoint: 'oss-cn-shenzhen.aliyuncs.com'
  bucket: 'mooc-manager'
  callbackUrl: ${ALIYUNCALLBACKHOST}/upload/uploadCallback
